apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanya-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanya
  template:
    metadata:
      labels:
        app: vanya
    spec:
      containers:
      - name: vanya
        image: vanya-app
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vanya-service
spec:
  selector:
    app: vanya
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
