apiVersion: apps/v1
kind: Deployment
metadata:
  name: vasya-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vasya
  template:
    metadata:
      labels:
        app: vasya
    spec:
      containers:
      - name: vasya
        image: vasya-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: vasya-service
spec:
  selector:
    app: vasya
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
