apiVersion: apps/v1
kind: Deployment
metadata:
  name: kirill-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kirill
  template:
    metadata:
      labels:
        app: kirill
    spec:
      containers:
      - name: kirill
        image: kirill-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kirill-service
spec:
  selector:
    app: kirill
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
